# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='Issue',
        ),
    ]
