# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='Features',
            new_name='Feature',
        ),
    ]
