# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_auto_20190910_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='Feature',
            new_name='name',
        ),
    ]
