# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0005_auto_20190910_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
