# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-19 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_do', '0009_auto_20190927_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
