# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-31 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0011_feature_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='timestamp',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='feature',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
