# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
