# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-08 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0014_feedback_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user_name',
            new_name='name',
        ),
    ]
