# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-17 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0015_auto_20200308_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='amount_needed',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
            preserve_default=False,
        ),
    ]
