# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-25 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0016_feature_amount_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='like_cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
    ]
