# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0017_feature_like_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='money_received',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=6),
            preserve_default=False,
        ),
    ]
