# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0018_feature_money_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='amount_needed',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6),
        ),
        migrations.AlterField(
            model_name='feature',
            name='like_cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
        migrations.AlterField(
            model_name='feature',
            name='money_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
