# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-22 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0019_auto_20200419_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name_person',
            field=models.CharField(blank=True, db_column='name', max_length=30),
        ),
        
    ]
