# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-18 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='checkout.Order')),
            ],
        ),
    ]
