# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_feature_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feature_products',
        ),
    ]
